login: &login
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password:

development: &development
  database: berlin_development
  <<: *login

test: &test
  database: berlin_test
  <<: *login

production: &production
  adapter: mysql2
  host: localhost
  database: your_production_database
  username: your_production_database_login
  password: your_production_database_password

